=== vungoctan1109/parser/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="user" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="personGr">
        <xs:sequence>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="phone" type="xs:integer"/>
            <xs:element name="age">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"></xs:minInclusive>
                        <xs:maxInclusive value="120"></xs:maxInclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="teacher">
        <xs:sequence>
            <xs:group ref="personGr"></xs:group>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="department" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="employee">
        <xs:sequence>
            <xs:group ref="personGr"></xs:group>
            <xs:element name="experience" type="xs:integer"/>
            <xs:element name="class" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="user">
        <xs:choice>
            <xs:element name="employee" type="employee"></xs:element>
            <xs:element name="teacher" type="teacher"></xs:element>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== vungoctan1109/parser/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.w3schools.com"
       xsi:schemaLocation="users.xsd">
    <user>
        <teacher id="1">
            <firstname>Vu</firstname>
            <lastname>Tan</lastname>
            <email>vntan1109@gmail.com</email>
            <phone>0943683686</phone>
            <age>21</age>
            <position>Hieu truong</position>
            <department>toa D</department>
        </teacher>
    </user>
    <user>
        <teacher id="2">
            <firstname>Vu</firstname>
            <lastname>A</lastname>
            <email>a@gmail.com</email>
            <phone>325235235</phone>
            <age>23</age>
            <position>Hieu pho</position>
            <department>toa C</department>
        </teacher>
    </user>
    <user>
        <employee id="1">
            <firstname>Vu</firstname>
            <lastname>Tu</lastname>
            <email>vntu1409@gmail.com</email>
            <phone>52957295725</phone>
            <age>30</age>
            <experience>2</experience>
            <class>2A</class>
        </employee>
    </user>
    <user>
        <employee id="2">
            <firstname>Vu</firstname>
            <lastname>Tu</lastname>
            <email>vntu109@gmail.com</email>
            <phone>23523523</phone>
            <age>23</age>
            <experience>2</experience>
            <class>2B</class>
        </employee>
    </user>
    <user>
        <employee id="3">
            <firstname>Vu</firstname>
            <lastname>Ta</lastname>
            <email>vntu109@gmail.com</email>
            <phone>23523523</phone>
            <age>23</age>
            <experience>2</experience>
            <class>3B</class>
        </employee>
    </user>
</users>
